### ISSUE TITLE
Doesn’t work with DMGs - "hdiutil: attach failed - Resource busy"

### ISSUE THREAD

**Issue by Stooovie** [fgr0/dmginstall#3]
Debugger returns "hdiutil: attach failed - Resource busy“. DMG mounts fine manually.

Any tips?

**Comment by fgr0** [comment]
@Stooovie as far as I can tell that particular error happens if the DMG is already mounted. The script doesn't check if a DMG is already mounted and just tries to mount it again, which fails. 

As you mentioned, there seems to be a general issue when trying to install DMGs, I *think* I found the problem and was able to fix it, but I haven't used Alfred (and therefore this workflow) in years and cannot test this fixed version. I can make **no guarantees** that this will work at all, but you are welcome to try. [app_install-dmg-fix-v1.0.1.alfredworkflow.zip](https://github.com/fgr0/dmginstall/files/3221099/app_install-dmg-fix-v1.0.1.alfredworkflow.zip)

**Comment by Stooovie** [comment]
Hi! Thanks, but this workflow doesn’t install into Alfred at all (nothing happens upon dragging it into Alfred or doubleclicking it. Never mind, thanks anyway.
